### ISSUE TITLE
Product Title and Rating is not showing in Popup

### ISSUE THREAD

**Issue by Chandrasekhar1211** [addonify/addonify-quick-view#149]
Hi, thanks for the plugin. I have selected all options in the dashboard, but the product title and rating is not coming inside the quick view modal.
![image](https://user-images.githubusercontent.com/106801870/233573501-89e3ec96-d8a0-4e73-b61f-ac6266511171.png)
![image](https://user-images.githubusercontent.com/106801870/233573689-c9487dff-4515-490c-be93-1a976fbca57d.png)
Can you please help me on this?

**Comment by Asok17** [comment]
Hi,

Could you share your website's link? It would be helpful for the problem inspection.

**Comment by Chandrasekhar1211** [comment]
> 

Sure @Asok17, @addonify here it is: https://flywheelstaging.com/

**Comment by Asok17** [comment]
Hi,

Now I can see the product title being displayed. Have you made any changes @Chandrasekhar1211?

**Comment by Chandrasekhar1211** [comment]
Yes, we found that we lost the class title. Added it again in title.php

**Comment by Asok17** [comment]
For displaying all the elements of the quick view content. We have used the default functions from WooCommerce. If you have override them, it would not be displayed. Below are the functions we have used in the quick view content,
~~~
- woocommerce_show_product_sale_flash
- woocommerce_show_product_images
- woocommerce_template_single_title
- woocommerce_template_single_rating
- woocommerce_template_single_price
- woocommerce_template_single_excerpt
- woocommerce_template_single_add_to_cart
- woocommerce_template_single_meta
~~~

**Comment by Chandrasekhar1211** [comment]
Sure thank you @Asok17 . Let me know is there any function to enable the character limit for product excerpt?

**Comment by Asok17** [comment]
We have used the function `woocommerce_template_single_excerpt` to display the product excerpt. I guess you @Chandrasekhar1211  will have to look into it for more information.

**Comment by Chandrasekhar1211** [comment]
Okay, @Asok17! And the reviews are coming now. Thank you. You can mark it as completed. Thank you for your timely response.
