### ISSUE TITLE
Product Slider Crashed

### ISSUE THREAD

**Issue by Chandrasekhar1211** [addonify/addonify-quick-view#174]
![image](https://github.com/addonify/addonify-quick-view/assets/106801870/2e121bc1-b622-48fa-bd6b-cec72907d03a)
Hi @h1dd3nsn1p3r May I know why my product slider got crashed? I disabled all the minification and cleared the cache as well. I didn't see any console errors as well. But, still causing this issue.

Open this page: https://ornery-country.flywheelstaging.com/ in a private window and click on the  "shop" in the menu. Open the popup of any product which has a slider. Let me know the issue and solution for it. Thanks in advance.

**Comment by h1dd3nsn1p3r** [comment]
Hi @Chandrasekhar1211 

I am not sure why it crashed. I don't think this is Addonify quick view issue. 

![image](https://github.com/addonify/addonify-quick-view/assets/21140404/6316f852-5eef-4ef7-a899-380bf8024f0a)

I just checked, The Flex slider has been working fine on your homepage, PDP but it seems to be broken on the shop catalogue page. 

Please check if the support of Photoswipe & Flexslider is disabled on the shop page some other way. It could be a custom filter or plugins (Optimizer). 

I hope this helps.

**Comment by Chandrasekhar1211** [comment]
@h1dd3nsn1p3r  Even if you go back to the home and open then it will break. For the first time when you open a page directly in a private window, it is loading fine. After loading on any other page, there the popup got broken

**Comment by Chandrasekhar1211** [comment]
@h1dd3nsn1p3r I used asset cleanup plugin to unload some unwanted files on this page which causing this issue.

**Comment by h1dd3nsn1p3r** [comment]
Can you confirm **asset cleanup plugin** is causing the problem?

**Comment by Chandrasekhar1211** [comment]
Yeah, when I disable all the setup options on that specific page, it's became normal.

**Comment by h1dd3nsn1p3r** [comment]
Got it! Like I said this issue had nothing to do with Addonify Quick View itself. 

I am closing this issue.

**Comment by Chandrasekhar1211** [comment]
Fine. Thank you.
